import { default as Product } from '../models/product';

export const PRODUCTS: Product[] = [
  { _id: '1',
    name: 'piza',
    description: 'something1',
    makerID: '11',
    makerName: 'pizale',
    quantity: 26,
    //isAvailable: true,
    price: 0,
    phone: '0506558545',
    address: 'jerusalem',
    url: 'assets/images/1.jpg' },

    { _id: '2',
    name: 'falafel',
    description: 'something2',
    makerID: '22',
    makerName: 'falafelia',
    quantity: 26,
   // isAvailable: true,
    price: 0,
    phone: '0506558335',
    address: 'elon-more',
    url: 'assets/images/2.jpg' },

    { _id: '8',
    name: 'בשר',
    description: 'something8',
    makerID: '88',
    makerName: 'הכפריה',
    quantity: 26,
    //isAvailable: true,
    price: 0,
    phone: '0506228335',
    address: 'bne_netzarim',
    url: 'assets/images/8.jpg' },

    { _id: '12',
    name: 'קציצות',
    description: 'something12',
    makerID: '1212',
    makerName: 'הסטקיה',
    quantity: 26,
   // isAvailable: true,
    price: 0,
    phone: '0506221235',
    address: 'באר שבע',
    url: 'assets/images/12.jpg' },

    { _id: '7',
    name: 'פאי רועים',
    description: 'something7',
    makerID: '77',
    makerName: 'הסטקיה',
    quantity: 26,
    //isAvailable: true,
    price: 0,
    phone: '0506277235',
    address: 'באר שבע',
    url: 'assets/images/7.jpg' },

    { _id: '9',
    name: 'עוף בתנור',
    description: 'something9',
    makerID: '99',
    makerName: 'הסטקיה',
    quantity: 26,
   // isAvailable: true,
    price: 0,
    phone: '0506997235',
    address: 'שכם',
    url: 'assets/images/9.jpg' }

];